SELECT * FROM tbl_stg_aw_data;
/*DDL- DATA DEFINATION LANGUAGE */

CREATE TABLE TBL_TRANS_HOP1_CUSTOMER(
CUSTOMERKEY INT,
CUSTOMER_NAME VARCHAR(50),
BIRTH_DATE DATE ,
AGE INT,
MARITAL_STATUS varchar(10),
GENDER VARCHAR(20),
EMAIL_ADDRESS varchar(50),
ANNUAL_INCOME int,
TOTAL_CHILDREN INT,
EDUCATION_LEVEL varchar(20),
OCCUPATION VARCHAR(30),
HOME_OWNER VARCHAR(20)
);
USE ADVENTUREWORKS;



/*
DML-DATA MANUPULATION LANGUAGE 
DELETE
INSERT
UPDATE
*/
/*BEFORE DELETE THE TABLE YOU HAVE TO USE THIS COMMAND */
SET SQL_SAFE_UPDATE = 0;
DELETE FROM tbl_trans_hop1_customer;

/*THIS IS HOW YOU INSERT THE DATA */
INSERT INTO tbl_trans_hop1_customer
SELECT  DISTINCT
customerkey,
CONCAT(prefix,' ',firstname,' ',lastname) AS CUSTOMER_NAME,
birthdate,
DATEDIFF(CURRENT_DATE(),birthdate)/365 AS AGE,
CASE WHEN maritalstatus = 'S' THEN 'SINGLE'
		ELSE 'MARRIED'
END maritalstatus,
CASE WHEN gender = 'M' THEN 'MALE'
	WHEN gender = 'F' THEN 'FEMALE'
    ELSE 'DID NOT DISCLOSED'
END gender,
emailaddress,
annualincome,
totalchildren,
educationlevel,
occupation,
CASE WHEN homeowner = 'Y' THEN 'YES'
ELSE 'NO'
END homeowner
FROM TBL_STG_AW_DATA;

/*ALL DISTINCT DATA ENTERED INTO THIS TABLE */
SELECT COUNT(*) FROM tbl_trans_hop1_customer;

CREATE TABLE TBL_TRANS_HOP1_PROD(
ProductSubcategoryKey INT,
ProductSKU VARCHAR(30),
ProductName VARCHAR(40),
ModelName VARCHAR(35),
ProductDescription VARCHAR(250),
ProductColor VARCHAR(10),
ProductSize CHAR(3),
ProductStyle CHAR(2),
ProductCost DECIMAL(6,2),
ProductPrice DECIMAL(6,2)
);
DESC TBL_TRANS_HOP1_PROD;

/*INSERT DATA INTO TABLE */
INSERT INTO tbl_trans_hop1_prod
SELECT DISTINCT
ProductSubcategoryKey ,
ProductSKU ,
ProductName ,
ModelName ,
ProductDescription ,
ProductColor ,
ProductSize ,
ProductStyle ,
ProductCost ,
ProductPrice
FROM tbl_stg_aw_data;

SELECT COUNT(*) FROM tbl_trans_hop1_prod;
SELECT * FROM tbl_trans_hop1_prod;


CREATE TABLE TBL_TRANS_HOP1_PRDCAT (
  PRODUCTCATEGORYKEY INT,
  CATEGORYNAME VARCHAR(15)  
);

INSERT INTO TBL_TRANS_HOP1_PRDCAT
SELECT DISTINCT
PRODUCTCATEGORYKEY,
CATEGORYNAME
FROM TBL_STG_AW_DATA;


CREATE TABLE TBL_TRANS_HOP1_PRDSUBCAT (
  PRODUCTSUBCATEGORYKEY INT,
  SUBCATEGORYNAME VARCHAR(20),
  PRODUCTCATEGORYKEY INT
);
INSERT INTO TBL_TRANS_HOP1_PRDSUBCAT
SELECT DISTINCT 
PRODUCTSUBCATEGORYKEY,
SUBCATEGORYNAME,
PRODUCTCATEGORYKEY
FROM TBL_STG_AW_DATA;

CREATE TABLE TBL_TRANS_HOP1_TERRITORY (
  SALESTERRITORYKEY INT,
  REGION VARCHAR(15),
  COUNTRY VARCHAR(15),
  CONTINENT VARCHAR(15)
);
INSERT INTO TBL_TRANS_HOP1_TERRITORY
SELECT DISTINCT 
TERRITORYKEY,
REGION,
COUNTRY,
CONTINENT
FROM TBL_STG_AW_DATA;

CREATE TABLE TBL_TRANS_HOP1_SALES (
  ORDERDATE DATE,
  STOCKDATE DATE,
  PRODUCTKEY INT,
  CUSTOMERKEY INT,
  TERRITORYKEY INT,
  ORDERLINEITEM INT,
  ORDERQUANTITY INT
);

INSERT INTO TBL_TRANS_HOP1_SALES
SELECT 
ORDERDATE,
STOCKDATE,
PRODUCTKEY,
CUSTOMERKEY,
TERRITORYKEY,
ORDERLINEITEM,
ORDERQUANTITY
FROM TBL_STG_AW_DATA;


