SELECT * FROM tbl_stg_aw_data;
/*DDL- DATA DEFINATION LANGUAGE */

CREATE TABLE TBL_TRANS_HOP1_CUSTOMER(
CUSTOMERKEY INT,
CUSTOMER_NAME VARCHAR(50),
BIRTH_DATE DATE ,
AGE INT,
MARITAL_STATUS varchar(10),
GENDER VARCHAR(20),
EMAIL_ADDRESS varchar(50),
ANNUAL_INCOME int,
TOTAL_CHILDREN INT,
EDUCATION_LEVEL varchar(20),
OCCUPATION VARCHAR(30),
HOME_OWNER VARCHAR(20)
);



